const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),lines=fs.readFileSync(path.join(root,'data/articulos.csv'),'utf8').split(/\r?\n/);
const products=lines.slice(1).map(line=>line.split(';')).filter(c=>c.length>2).map(c=>({COD:c[0],ARTIC:c[1]}));
const storage=new Map(),windows=[];const elements={};
for(const id of ['comandasNotice','comandasTo','comandasNote','comandasQuick','comandasSearch','comandasMatches','comandasLines','comandasHistory','comandasModels','comandasDate'])elements[id]={value:'',textContent:'',innerHTML:''};
const ctx=vm.createContext({console,products,crypto:require('node:crypto').webcrypto,confirm:()=>true,prompt:()=> 'Reposición Recuplast',window:{open:(url)=>windows.push(url)},document:{getElementById:id=>elements[id]||null,querySelector:()=>({value:''})},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},normKey:s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim().replace(/\s+/g,' '),esc:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))});
vm.runInContext(fs.readFileSync(path.join(root,'assets/comandas.js'),'utf8'),ctx);
const evaluate=js=>vm.runInContext(js,ctx);
const a=evaluate('comandasParseQuick("rec int mate bl 6x1 + 4x4 + 3x10 + 3x20",products)');
assert.deepEqual(Array.from(a,x=>x.cod),['84520993','84520994','84520996','84520997']);
assert.deepEqual(Array.from(a,x=>x.qty),[6,4,3,3]);
const b=evaluate('comandasParseQuick("recumix int 1,25 y 5 kg",products)');
assert.deepEqual(Array.from(b,x=>x.presentation),['1,25 kg','5 kg']);
assert.equal(evaluate('comandasParseQuick("Tinta B",products)[0].cod'),'');
assert.equal(evaluate('comandasParseQuick("traer los que haya",products)[0].request'),'traer los que haya');
assert.equal(evaluate('comandasParseQuick("rec int mate bl 6x1 + 4x99",products).length'),1);
assert.equal(evaluate('comandasParseQuick("rec int mate bl 6x1 + 4x99",products)[0].cod'),'');
evaluate('comandasDraft.lines.push(...comandasParseQuick("rec int mate bl 6x1 + 4x4 + 3x10 + 3x20",products));comandasDraft.lines.push(...comandasParseQuick("recumix int 1,25 y 5 kg",products));comandasDraft.lines.push(...comandasParseQuick("Tinta B",products));');
elements.comandasTo.value='Depósito / hermano';elements.comandasNote.value='Traer hoy';
const record=evaluate('comandasSave()');assert(record);assert.equal(JSON.parse(storage.get('pk_comandas_history_v1')).length,1);
const message=evaluate('comandasMessage(comandasHistoryData()[0])');assert.match(message,/6 x 1 L/);assert.match(message,/4 x 4 L/);assert.match(message,/1,25 kg/);assert.match(message,/TINTA B\n• traer/);assert.match(message,/Observación:\nTraer hoy/);
evaluate('comandasSend()');assert.equal(JSON.parse(storage.get('pk_comandas_history_v1')).length,1);assert.match(decodeURIComponent(windows[0]),/Comanda depósito - Pancko/);
evaluate('comandasModelFromDraft()');assert.equal(JSON.parse(storage.get('pk_comandas_models_v1')).length,1);
evaluate('comandasHistoryAction(comandasDraft.id,"received")');assert.equal(JSON.parse(storage.get('pk_comandas_history_v1'))[0].status,'received');
assert.equal(storage.has('pk_cart'),false);assert.equal(storage.has('pk_history'),false);assert.equal(storage.has('pk_cash_daily_v1'),false);
elements.comandasLineCount={textContent:''};
evaluate('comandasDraft.lines=Array.from({length:20},(_,i)=>comandasFreeLine("Producto "+(i+1)));comandasExpandedId=null;comandasRenderLines()');
assert.equal((elements.comandasLines.innerHTML.match(/class="comandas-line /g)||[]).length,20);
assert.equal((elements.comandasLines.innerHTML.match(/class="comandas-line is-open"/g)||[]).length,0);
assert.equal(elements.comandasLineCount.textContent,'20 ítems');
evaluate('comandasToggle(0)');
assert.equal((elements.comandasLines.innerHTML.match(/class="comandas-line is-open"/g)||[]).length,1);
evaluate('comandasToggle(8)');
assert.equal((elements.comandasLines.innerHTML.match(/class="comandas-line is-open"/g)||[]).length,1);
assert.match(elements.comandasLines.innerHTML,/id="comandasLine8"/);
assert.match(elements.comandasLines.innerHTML,/id="comandasLineToggle8" aria-expanded="true"/);
elements.comandasLineSummary8={textContent:''};
evaluate('comandasChange(8,"qty","4")');
assert.equal(elements.comandasLineSummary8.textContent,'4 unidades');
evaluate('comandasToggle(8)');
assert.equal((elements.comandasLines.innerHTML.match(/class="comandas-line is-open"/g)||[]).length,0);
const mobileCss=fs.readFileSync(path.join(root,'assets/comandas.css'),'utf8');
assert.match(mobileCss,/@media\(max-width:650px\)/);
assert.match(mobileCss,/\.comandas-line-editor\{display:none/);
assert.match(mobileCss,/\.comandas-line\.is-open \.comandas-line-editor\{display:block/);
console.log('OK Comandas: parser real, texto libre, ambigüedad, WhatsApp, guardado idempotente, modelo, recibida y aislamiento local.');
