const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),lines=fs.readFileSync(path.join(root,'data/articulos.csv'),'utf8').split(/\r?\n/);
const products=lines.slice(1).map(line=>line.split(';')).filter(c=>c.length>2).map(c=>({COD:c[0],ARTIC:c[1]}));
const storage=new Map(),windows=[];const elements={};
for(const id of ['comandasNotice','comandasTo','comandasNote','comandasProduct','comandasQuantity','comandasClearProduct','comandasMatches','comandasLines','comandasHistory','comandasModels','comandasDate'])elements[id]={value:'',textContent:'',innerHTML:'',hidden:false,focus(){this.focused=true}};
const ctx=vm.createContext({console,products,crypto:require('node:crypto').webcrypto,confirm:()=>true,prompt:()=> 'Reposición Recuplast',window:{open:(url)=>windows.push(url)},document:{getElementById:id=>elements[id]||null,querySelector:()=>({value:''})},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},normKey:s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim().replace(/\s+/g,' '),esc:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))});
vm.runInContext(fs.readFileSync(path.join(root,'assets/comandas.js'),'utf8'),ctx);
const evaluate=js=>vm.runInContext(js,ctx);
for(const [query,expected] of [['nal int','PROFESIONAL INTERIOR'],['int mate bl','RECUPLAST INT MATE BLANCO'],['techos bl','RECUPLAST TECHOS BLANCO'],['recumix int','RECUMIX INTERIOR']]){
  const names=evaluate(`comandasCatalogMatches(${JSON.stringify(query)},products).map(p=>p.ARTIC)`);
  assert(names.some(name=>name.includes(expected)),`${query} debe encontrar ${expected}`);
}
evaluate('comandasDraft.lines=[]');
elements.comandasProduct.value='nal int';evaluate('comandasSearch()');
assert.match(elements.comandasMatches.innerHTML,/PROFESIONAL INTERIOR/);
const pro=products.find(p=>p.ARTIC==='PROFESIONAL INTERIOR BLANCO 1 LTS');
evaluate(`comandasSelectArticle(${JSON.stringify(pro.COD)})`);
assert.equal(evaluate('comandasDraft.lines.length'),0,'seleccionar no debe agregar');
assert.equal(elements.comandasProduct.value,pro.ARTIC);
assert.equal(elements.comandasQuantity.focused,true);
elements.comandasQuantity.value='6x1';evaluate('comandasAddQuick()');
assert.equal(evaluate('comandasDraft.lines.length'),1);
assert.equal(evaluate('comandasDraft.lines[0].qty'),6);
assert.equal(evaluate('comandasDraft.lines[0].presentation'),'1 L');
assert.equal(elements.comandasProduct.value,'');
evaluate('comandasDraft.lines=[]');
elements.comandasProduct.value='int mate bl';evaluate('comandasSearch()');
const rec4=products.find(p=>p.ARTIC==='RECUPLAST INT MATE BLANCO 4 LTS');
evaluate(`comandasSelectArticle(${JSON.stringify(rec4.COD)})`);
assert.equal(evaluate('comandasDraft.lines.length'),0);
elements.comandasQuantity.value='6x1';evaluate('comandasAddQuick()');
assert.equal(evaluate('comandasDraft.lines[0].cod'),'84520993');
assert.equal(evaluate('comandasDraft.lines[0].product'),'RECUPLAST INT MATE BLANCO');
assert.equal(evaluate('comandasLineSummary(comandasDraft.lines[0])'),'6 × 1 L');
evaluate('comandasDraft.lines=[]');
elements.comandasProduct.value='tinta i';elements.comandasQuantity.value='1 caja';evaluate('comandasAddQuick()');
assert.equal(evaluate('comandasDraft.lines[0].product'),'TINTE I');
assert.equal(evaluate('comandasDraft.lines[0].request'),'1 caja');
assert.match(evaluate('comandasLineSummary(comandasDraft.lines[0])'),/1 caja/);
evaluate('comandasDraft.lines=[]');
for(const [quantity,expected] of [['6*1','6 × 1 L'],['3x20lt','3 × 20 L'],['2','2 unidades'],['traer','traer'],['los que haya','los que haya'],['surtido','surtido']]){
  const line=evaluate(`comandasEntryLine("Producto",${JSON.stringify(quantity)},null,products)`);
  assert.equal(evaluate(`comandasLineSummary(${JSON.stringify(line)})`),expected,quantity);
}
elements.comandasProduct.value='recumix int';evaluate('comandasSearch()');
evaluate(`comandasSelectArticle(${JSON.stringify(products.find(p=>p.ARTIC==='RECUMIX INTERIOR 5 KG').COD)})`);
evaluate('comandasClearProduct()');
assert.equal(elements.comandasProduct.value,'');assert.equal(evaluate('comandasSelectedArticle'),null);
assert.equal(evaluate('comandasDraft.lines.length'),0);
const a=evaluate('comandasParseQuick("rec int mate bl 6x1 + 4x4 + 3x10 + 3x20",products)');
assert.deepEqual(Array.from(a,x=>x.cod),['84520993','84520994','84520996','84520997']);
assert.deepEqual(Array.from(a,x=>x.qty),[6,4,3,3]);
const b=evaluate('comandasParseQuick("recumix int 1,25 y 5 kg",products)');
assert.deepEqual(Array.from(b,x=>x.presentation),['1,25 kg','5 kg']);
assert.equal(evaluate('comandasParseQuick("Tinta B",products)[0].cod'),'');
assert.equal(evaluate('comandasParseQuick("traer los que haya",products)[0].request'),'traer los que haya');
assert.equal(evaluate('comandasParseQuick("rec int mate bl 6x1 + 4x99",products).length'),1);
assert.equal(evaluate('comandasParseQuick("rec int mate bl 6x1 + 4x99",products)[0].cod'),'');
evaluate('comandasDraft.lines.push(...comandasParseQuick("rec int mate bl 6x1 + 4x4 + 3x10 + 3x20",products));comandasDraft.lines.push(...comandasParseQuick("recumix int 1,25 y 5 kg",products));comandasDraft.lines.push(...comandasParseQuick("Tinta B",products));');
elements.comandasTo.value='Depósito / hermano';elements.comandasNote.value='Traer hoy';
const record=evaluate('comandasSave()');assert(record);assert.equal(JSON.parse(storage.get('pk_comandas_history_v1')).length,1);
const message=evaluate('comandasMessage(comandasHistoryData()[0])');assert.match(message,/6 x 1 L/);assert.match(message,/4 x 4 L/);assert.match(message,/1,25 kg/);assert.match(message,/TINTA B\n• traer/);assert.match(message,/Observación:\nTraer hoy/);
evaluate('comandasSend()');assert.equal(JSON.parse(storage.get('pk_comandas_history_v1')).length,1);assert.match(decodeURIComponent(windows[0]),/Comanda depósito - Pancko/);
evaluate('comandasModelFromDraft()');assert.equal(JSON.parse(storage.get('pk_comandas_models_v1')).length,1);
evaluate('comandasHistoryAction(comandasDraft.id,"received")');assert.equal(JSON.parse(storage.get('pk_comandas_history_v1'))[0].status,'received');
assert.equal(storage.has('pk_cart'),false);assert.equal(storage.has('pk_history'),false);assert.equal(storage.has('pk_cash_daily_v1'),false);
elements.comandasLineCount={textContent:''};
evaluate('comandasDraft.lines=Array.from({length:20},(_,i)=>comandasFreeLine("Producto "+(i+1)));comandasExpandedId=null;comandasRenderLines()');
assert.equal((elements.comandasLines.innerHTML.match(/class="comandas-line /g)||[]).length,20);
assert.equal((elements.comandasLines.innerHTML.match(/class="comandas-line is-open"/g)||[]).length,0);
assert.equal(elements.comandasLineCount.textContent,'20 ítems');
evaluate('comandasToggle(0)');
assert.equal((elements.comandasLines.innerHTML.match(/class="comandas-line is-open"/g)||[]).length,1);
evaluate('comandasToggle(8)');
assert.equal((elements.comandasLines.innerHTML.match(/class="comandas-line is-open"/g)||[]).length,1);
assert.match(elements.comandasLines.innerHTML,/id="comandasLine8"/);
assert.match(elements.comandasLines.innerHTML,/id="comandasLineToggle8" aria-expanded="true"/);
elements.comandasLineSummary8={textContent:''};
evaluate('comandasChange(8,"qty","4")');
assert.equal(elements.comandasLineSummary8.textContent,'4 unidades');
evaluate('comandasToggle(8)');
assert.equal((elements.comandasLines.innerHTML.match(/class="comandas-line is-open"/g)||[]).length,0);
const mobileCss=fs.readFileSync(path.join(root,'assets/comandas.css'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.match(html,/id="comandasProduct"/);assert.match(html,/id="comandasQuantity"/);
assert.doesNotMatch(html,/id="comandasQuick"/);assert.doesNotMatch(html,/id="comandasSearch"/);
assert.match(mobileCss,/@media\(max-width:650px\)/);
assert.match(mobileCss,/\.comandas-line-editor\{display:none/);
assert.match(mobileCss,/\.comandas-line\.is-open \.comandas-line-editor\{display:block/);
console.log('OK Comandas: parser real, texto libre, ambigüedad, WhatsApp, guardado idempotente, modelo, recibida y aislamiento local.');
