const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const gs=fs.readFileSync(path.join(root,'backend/Pancko_AppsScript_v0.12.31.gs'),'utf8');
const source=gs.slice(gs.indexOf('const RECIPE_HEADERS_='));
const records=[];const headers=['clave','revision','actualizado_en','op_ids_json','receta_json'];
const sh={getLastRow(){return records.length+1},getRange(row,col,count){return {getValues(){return records.slice(row-2,row-2+count)},setValues(v){records[row-2]=v[0]}}}};
const ctx={VERSION:'0.12.31',Date,JSON,Number,String,Array,Error,RECIPE_HEADERS_:undefined,getOrCreateSheet_:()=>sh,ss_:()=>({getSheetByName:()=>records.length?sh:null}),headers_:()=>headers,rowObject_:(h,v)=>Object.fromEntries(h.map((k,i)=>[k,v[i]])),valuesByHeaders_:(h,obj)=>h.map(k=>obj[k]??'')};
vm.createContext(ctx);vm.runInContext(source,ctx);
const normal={base:'PASTEL',idcolor:'T001',codigo_formula:'T001',descripcion:'Gris propio',formula_1l:'B=1.25 | C=2',tipo_receta:'NORMAL'};
let p={key:'NORMAL|PASTEL|T001',op_id:'recipe_123456789abc',row:normal,revision:0};
let first=ctx.recipeApply_(p);assert.equal(first.revision,1);assert.equal(records.length,1);
let retry=ctx.recipeApply_(p);assert.equal(retry.duplicate,true);assert.equal(records.length,1);
let stale=ctx.recipeApply_({...p,op_id:'recipe_999999999abc',row:{...normal,formula_1l:'B=2'}});assert.equal(stale.conflict,true);assert.equal(records.length,1);
let newer=ctx.recipeApply_({...p,revision:1,op_id:'recipe_999999999abc',row:{...normal,formula_1l:'B=2'}});assert.equal(newer.revision,2);
assert.equal(ctx.recipesGet_().recipes[0].row.formula_1l,'B=2');
assert.throws(()=>ctx.recipeApply_({...p,op_id:'recipe_other123456',revision:2,row:{...normal,base:'DEEP'}}),/Clave/);
const special={base:'SPECIAL:MICROCEMENTO_PASTA',idcolor:'M001',codigo_formula:'M001',descripcion:'Micro gris',formula_pulsos:'B=2,2 | C=1,16',tipo_receta:'SPECIAL',familia_especial:'MICROCEMENTO_PASTA',articulo_patron_cod:'86921004',contenido_patron:'5',unidad_patron:'KG'};
assert.equal(ctx.recipeApply_({key:'SPECIAL|MICROCEMENTO_PASTA|86921004|M001',op_id:'recipe_special123456',revision:0,row:special}).revision,1);
assert.throws(()=>ctx.recipeApply_({key:'SPECIAL|MICROCEMENTO_PASTA|86921007|M002',op_id:'recipe_special999999',revision:0,row:{...special,codigo_formula:'M002',articulo_patron_cod:'86921007'}}),/COD patrón/);
console.log('OK recetas compartidas: alta, reintento idempotente, conflicto de revisión, NORMAL y validación SPECIAL.');
